const studioDb = window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.publishableKey);
const canvas = document.getElementById('studio-canvas'), ctx = canvas.getContext('2d'), mediaInput = document.getElementById('studio-media'), mediaHint = document.getElementById('media-hint'), studioMessage = document.getElementById('studio-message'), handleInput = document.getElementById('studio-handle'), watermarkEnabled = document.getElementById('watermark-enabled'), firstImageControl = document.getElementById('first-image-control'), firstImageSelect = document.getElementById('first-image');
const brandLogo = new Image(); brandLogo.src = 'assets/images/icon.png';
handleInput.value = localStorage.getItem('marketplace-tiktok-handle') || '@Marketplace.Finds';
handleInput.addEventListener('input', () => localStorage.setItem('marketplace-tiktok-handle', handleInput.value.trim()));
let mode = 'images', images = [], video = null, exporting = false, clipStart = performance.now(), firstImageIndex = 0;

function rr(x, y, w, h, r) { ctx.beginPath(); ctx.roundRect(x, y, w, h, r); }
function lines(text, max, font) { ctx.font = font; const out = []; let line = ''; (text || '').split(/\s+/).forEach((word) => { const next = line ? `${line} ${word}` : word; if (ctx.measureText(next).width > max && line) { out.push(line); line = word; } else line = next; }); if (line) out.push(line); return out.slice(0, 2); }
function contain(media, x, y, w, h) { const sw = media.videoWidth || media.naturalWidth || 1, sh = media.videoHeight || media.naturalHeight || 1, s = Math.min(w / sw, h / sh), dw = sw * s, dh = sh * s; ctx.drawImage(media, x + (w - dw) / 2, y + (h - dh) / 2, dw, dh); }
function asset(elapsed) { return mode === 'video' ? video : images.length ? images[(firstImageIndex + Math.floor(elapsed / 4000)) % images.length] : null; }
function value(id, fallback) { return document.getElementById(id).value || fallback; }
function videoLength() { const field = document.getElementById('video-length'); const seconds = Math.min(60, Math.max(5, Number(field.value) || 20)); field.value = seconds; return seconds; }
function ease(t) { t = Math.max(0, Math.min(1, t)); return t * t * (3 - 2 * t); }
function stage(seconds, start, end, exitFade) { return ease((seconds - start) / (end - start)) * exitFade; }

function render(now = performance.now()) {
  const duration = videoLength(), elapsed = (now - clipStart) / 1000, p = (elapsed / duration) % 1, exitFade = 1 - ease((p - .92) / .08), productMotion = stage(elapsed, 0, .90, exitFade), cardMotion = stage(elapsed, .06, .55, exitFade), hookMotion = stage(elapsed, .14, .46, exitFade), titleMotion = stage(elapsed, .25, .72, exitFade), benefitMotion = stage(elapsed, .40, .88, exitFade), priceMotion = stage(elapsed, .52, 1.00, exitFade), ctaMotion = stage(elapsed, .62, 1.10, exitFade), footerMotion = stage(elapsed, .72, 1.18, exitFade);
  const bg = ctx.createLinearGradient(0, 0, 1080, 1920); bg.addColorStop(0, '#123e8d'); bg.addColorStop(.55, '#071d47'); bg.addColorStop(1, '#030c21'); ctx.fillStyle = bg; ctx.fillRect(0, 0, 1080, 1920);
  ctx.fillStyle = 'rgba(255,157,0,.13)'; ctx.beginPath(); ctx.arc(100, 1540 + Math.sin(now / 1900) * 35, 270, 0, 7); ctx.fill();
  if (brandLogo.complete) ctx.drawImage(brandLogo, 70, 27, 124, 124); ctx.fillStyle = '#fff'; ctx.font = '800 42px Arial'; ctx.fillText('MARKETPLACE', 220, 82); const brandWidth = ctx.measureText('MARKETPLACE').width; ctx.fillStyle = '#ff9d00'; ctx.fillText('FINDS', 235 + brandWidth, 82); ctx.fillStyle = 'rgba(255,255,255,.82)'; ctx.font = '700 26px Arial'; ctx.fillText(handleInput.value || '@Marketplace.Finds', 220, 122);
  rr(70, 190, 940, 850, 42); ctx.fillStyle = '#f9fafc'; ctx.fill(); ctx.save(); rr(70, 190, 940, 850, 42); ctx.clip();
  const item = asset(elapsed * 1000); if (item && (item.complete || item.readyState >= 2)) { ctx.globalAlpha = productMotion; if (mode === 'video') { contain(item, 100, 220, 880, 790); } else { const enter = ease(elapsed / .90), exiting = ease((p - .92) / .08), zoom = 1.18 - (.18 * enter) + (.08 * exiting), shift = ((1 - enter) * 56) - (exiting * 28); ctx.translate(540, 615 + shift); ctx.scale(zoom, zoom); ctx.translate(-540, -615); contain(item, 100, 220, 880, 790); } } else { ctx.fillStyle = '#e7ebf1'; ctx.fillRect(70, 190, 940, 850); ctx.fillStyle = '#63708a'; ctx.font = '700 34px Arial'; ctx.textAlign = 'center'; ctx.fillText('Add your product image or video', 540, 620); ctx.textAlign = 'left'; } ctx.restore();
  if (watermarkEnabled.checked) { ctx.globalAlpha = productMotion; rr(118, 968, 258, 46, 16); ctx.fillStyle = 'rgba(7,27,67,.52)'; ctx.fill(); ctx.fillStyle = 'rgba(255,255,255,.88)'; ctx.font = '700 20px Arial'; ctx.textAlign = 'center'; ctx.fillText(handleInput.value || '@Marketplace.Finds', 247, 998); ctx.textAlign = 'left'; ctx.globalAlpha = 1; }
  ctx.save(); ctx.globalAlpha = cardMotion; ctx.translate(0, (1 - cardMotion) * 38); rr(70, 1080, 940, 430, 38); ctx.fillStyle = 'rgba(255,255,255,.97)'; ctx.fill(); ctx.restore();
  ctx.save(); ctx.globalAlpha = hookMotion; ctx.translate((1 - hookMotion) * -26, 0); ctx.fillStyle = '#ff9d00'; ctx.font = '800 25px Arial'; ctx.fillText(value('studio-hook', 'A smart find for everyday life').toUpperCase(), 118, 1140); ctx.restore();
  ctx.save(); ctx.globalAlpha = titleMotion; ctx.translate(0, (1 - titleMotion) * 26); ctx.fillStyle = '#102552'; ctx.font = '800 56px Arial'; let y = 1210; lines(value('studio-title', 'Your Product'), 820, ctx.font).forEach((line) => { ctx.fillText(line, 118, y); y += 64; }); ctx.restore();
  ctx.save(); ctx.globalAlpha = benefitMotion; ctx.translate(0, (1 - benefitMotion) * 18); ctx.fillStyle = '#526788'; ctx.font = '600 27px Arial'; let benefitY = 1248 + (lines(value('studio-title', 'Your Product'), 820, '800 56px Arial').length * 64); lines(value('studio-benefit', 'Add one useful benefit here'), 800, ctx.font).forEach((line) => { ctx.fillText(line, 118, benefitY); benefitY += 42; }); ctx.restore();
  ctx.save(); ctx.globalAlpha = priceMotion; ctx.translate((1 - priceMotion) * -38, 0); rr(118, 1428, 310, 66, 20); ctx.fillStyle = '#102552'; ctx.fill(); ctx.fillStyle = '#fff'; ctx.font = '800 30px Arial'; ctx.fillText(value('studio-price', 'AED -'), 146, 1472); ctx.restore();
  ctx.save(); ctx.globalAlpha = ctaMotion; ctx.translate((1 - ctaMotion) * 38, 0); rr(675, 1428, 285, 66, 20); ctx.fillStyle = '#ff9d00'; ctx.fill(); ctx.fillStyle = '#071b43'; ctx.font = '800 23px Arial'; ctx.textAlign = 'center'; ctx.fillText(value('studio-cta', 'Find it on Amazon'), 818, 1471); ctx.restore();
  ctx.globalAlpha = 1; ctx.textAlign = 'left'; requestAnimationFrame(render);
}
function clearMedia() { images.forEach((x) => URL.revokeObjectURL(x.src)); images = []; if (video) URL.revokeObjectURL(video.src); video = null; firstImageIndex = 0; firstImageSelect.innerHTML = ''; firstImageControl.hidden = true; }
function setMode(next) { mode = next; clearMedia(); mediaInput.value = ''; const isVideo = mode === 'video'; mediaInput.accept = isVideo ? 'video/mp4,video/webm,video/quicktime' : 'image/png,image/jpeg,image/webp'; mediaInput.multiple = !isVideo; mediaHint.textContent = isVideo ? 'Choose one product video' : 'Choose up to 5 images'; }
mediaInput.addEventListener('change', async () => { clearMedia(); studioMessage.textContent = ''; const files = [...mediaInput.files]; if (!files.length) return; if (mode === 'video') { video = document.createElement('video'); video.src = URL.createObjectURL(files[0]); video.muted = true; video.loop = true; video.playsInline = true; const loaded = await new Promise((done) => { video.onloadeddata = () => done(true); video.onerror = () => done(false); }); if (!loaded) { studioMessage.textContent = 'This video could not be previewed. Please use an H.264 MP4, WebM, or MOV file.'; video = null; return; } await video.play().catch(() => {}); studioMessage.style.color = '#257449'; studioMessage.textContent = `Video ready. The export will use the first ${videoLength()} seconds.`; } else { images = (await Promise.all(files.slice(0, 5).map((file) => new Promise((done) => { const image = new Image(); image.src = URL.createObjectURL(file); image.dataset.fileName = file.name; image.onload = () => done(image); image.onerror = () => done(null); })))).filter(Boolean); images.forEach((image, index) => { const option = document.createElement('option'); option.value = index; option.textContent = `Image ${index + 1}: ${image.dataset.fileName}`; firstImageSelect.append(option); }); firstImageControl.hidden = images.length < 2; studioMessage.style.color = '#257449'; studioMessage.textContent = images.length > 1 ? `${images.length} images ready. Each image stays on screen for 4 seconds.` : 'Image ready.'; } clipStart = performance.now(); });
firstImageSelect.addEventListener('change', () => { firstImageIndex = Number(firstImageSelect.value) || 0; clipStart = performance.now(); });
document.querySelectorAll('input[name="media-mode"]').forEach((el) => el.addEventListener('change', () => setMode(el.value)));
function download(blob, name) { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
document.getElementById('download-image').addEventListener('click', () => canvas.toBlob((blob) => download(blob, 'marketplace-finds-cover.png'), 'image/png'));
document.getElementById('download-video').addEventListener('click', async () => { if (exporting) return; exporting = true; const button = document.getElementById('download-video'), choice = document.getElementById('video-format').value, duration = videoLength(); const mp4Type = MediaRecorder.isTypeSupported('video/mp4;codecs=avc1') ? 'video/mp4;codecs=avc1' : MediaRecorder.isTypeSupported('video/mp4') ? 'video/mp4' : ''; const type = choice === 'webm' ? 'video/webm;codecs=vp9' : choice === 'mp4' ? (mp4Type || 'video/webm;codecs=vp9') : (mp4Type || 'video/webm;codecs=vp9'); const extension = type.startsWith('video/mp4') ? 'mp4' : 'webm'; button.disabled = true; button.textContent = 'Creating video...'; const recorder = new MediaRecorder(canvas.captureStream(30), { mimeType: MediaRecorder.isTypeSupported(type) ? type : 'video/webm', videoBitsPerSecond: 6000000 }); const chunks = []; recorder.ondataavailable = (e) => e.data.size && chunks.push(e.data); recorder.onstop = () => { download(new Blob(chunks, { type: recorder.mimeType }), `marketplace-finds-tiktok-video.${extension}`); button.disabled = false; button.textContent = 'Download video'; exporting = false; studioMessage.style.color = '#257449'; studioMessage.textContent = extension === 'mp4' ? 'MP4 video downloaded.' : 'WebM video downloaded. TikTok accepts WebM uploads.'; }; if (video) { video.currentTime = 0; await video.play().catch(() => {}); } clipStart = performance.now(); recorder.start(); setTimeout(() => { recorder.stop(); if (video) video.pause(); }, duration * 1000); });
document.getElementById('studio-sign-out').addEventListener('click', async () => { await studioDb.auth.signOut(); window.location.href = 'admin.html'; });
studioDb.auth.getSession().then(({ data: { session } }) => { if (!session) { window.location.href = 'admin.html'; return; } document.getElementById('studio-loading').hidden = true; document.getElementById('studio-shell').hidden = false; render(); });
