const studioDb = window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.publishableKey);
const canvas = document.getElementById('studio-canvas'), ctx = canvas.getContext('2d'), mediaInput = document.getElementById('studio-media'), mediaHint = document.getElementById('media-hint'), studioMessage = document.getElementById('studio-message'), handleInput = document.getElementById('studio-handle'), watermarkEnabled = document.getElementById('watermark-enabled'), imageOrderControl = document.getElementById('image-order-control'), imageOrderList = document.getElementById('image-order-list');
const brandLogo = new Image(); brandLogo.src = 'assets/images/icon.png';
handleInput.value = localStorage.getItem('marketplace-tiktok-handle') || '@Marketplace.Finds';
handleInput.addEventListener('input', () => localStorage.setItem('marketplace-tiktok-handle', handleInput.value.trim()));
let mode = 'images', images = [], video = null, exporting = false, clipStart = performance.now();

function rr(x, y, w, h, r) { ctx.beginPath(); ctx.roundRect(x, y, w, h, r); }
function lines(text, max, font) { ctx.font = font; const out = []; let line = ''; (text || '').split(/\s+/).forEach((word) => { const next = line ? `${line} ${word}` : word; if (ctx.measureText(next).width > max && line) { out.push(line); line = word; } else line = next; }); if (line) out.push(line); return out.slice(0, 2); }
function contain(media, x, y, w, h) { const sw = media.videoWidth || media.naturalWidth || 1, sh = media.videoHeight || media.naturalHeight || 1, s = Math.min(w / sw, h / sh), dw = sw * s, dh = sh * s; ctx.drawImage(media, x + (w - dw) / 2, y + (h - dh) / 2, dw, dh); }
function asset(elapsed) { return mode === 'video' ? video : images.length ? images[Math.floor(elapsed / 4000) % images.length] : null; }
function value(id, fallback) { return document.getElementById(id).value || fallback; }
function videoLength() { const field = document.getElementById('video-length'); const seconds = Math.min(60, Math.max(5, Number(field.value) || 20)); field.value = seconds; return seconds; }
function ease(t) { t = Math.max(0, Math.min(1, t)); return t * t * (3 - 2 * t); }
function stage(seconds, start, end, exitFade) { return ease((seconds - start) / (end - start)) * exitFade; }

function render(now = performance.now()) {
  const duration = videoLength(), elapsed = (now - clipStart) / 1000, p = (elapsed / duration) % 1, exitFade = 1 - ease((p - .97) / .03), productMotion = stage(elapsed, 0, .90, exitFade), cardMotion = stage(elapsed, .06, .55, exitFade), hookMotion = stage(elapsed, .14, .46, exitFade), titleMotion = stage(elapsed, .25, .72, exitFade), benefitMotion = stage(elapsed, .40, .88, exitFade), priceMotion = stage(elapsed, .52, 1.00, exitFade), ctaMotion = stage(elapsed, .62, 1.10, exitFade);
  const bg = ctx.createLinearGradient(0, 0, 1080, 1920); bg.addColorStop(0, '#0d3480'); bg.addColorStop(.48, '#061a44'); bg.addColorStop(1, '#020a1d'); ctx.fillStyle = bg; ctx.fillRect(0, 0, 1080, 1920);
  const blueGlow = ctx.createRadialGradient(170 + Math.sin(elapsed / 3) * 95, 1380 + Math.cos(elapsed / 4) * 95, 10, 170, 1380, 610); blueGlow.addColorStop(0, 'rgba(46,126,255,.42)'); blueGlow.addColorStop(.5, 'rgba(28,89,210,.14)'); blueGlow.addColorStop(1, 'rgba(7,26,71,0)'); ctx.fillStyle = blueGlow; ctx.fillRect(0, 0, 1080, 1920);
  const amberGlow = ctx.createRadialGradient(930 + Math.cos(elapsed / 4) * 50, 1460 + Math.sin(elapsed / 3.4) * 75, 8, 930, 1460, 340); amberGlow.addColorStop(0, 'rgba(255,157,0,.26)'); amberGlow.addColorStop(.42, 'rgba(255,123,0,.08)'); amberGlow.addColorStop(1, 'rgba(255,157,0,0)'); ctx.fillStyle = amberGlow; ctx.fillRect(0, 0, 1080, 1920);
  ctx.save(); ctx.globalAlpha = .38; ctx.strokeStyle = '#397cff'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(-70, 880 + Math.sin(elapsed / 4) * 36, 770, -.65, .98); ctx.stroke(); ctx.globalAlpha = .26; ctx.strokeStyle = '#ff9d00'; ctx.beginPath(); ctx.arc(1090, 1310 + Math.cos(elapsed / 3.7) * 28, 460, 2.12, 4.04); ctx.stroke(); ctx.restore();
  if (brandLogo.complete) ctx.drawImage(brandLogo, 70, 36, 112, 112); ctx.fillStyle = '#fff'; ctx.font = '800 40px Arial'; ctx.fillText('MARKETPLACE', 205, 84); const brandWidth = ctx.measureText('MARKETPLACE').width; ctx.fillStyle = '#ff9d00'; ctx.fillText('FINDS', 220 + brandWidth, 84); ctx.fillStyle = 'rgba(235,242,255,.84)'; ctx.font = '700 25px Arial'; ctx.fillText(handleInput.value || '@Marketplace.Finds', 205, 122);
  ctx.save(); ctx.shadowColor = 'rgba(1,10,35,.5)'; ctx.shadowBlur = 28; rr(70, 190, 940, 850, 42); ctx.fillStyle = 'rgba(4,24,66,.88)'; ctx.fill(); ctx.restore(); rr(70, 190, 940, 850, 42); ctx.strokeStyle = 'rgba(83,145,255,.78)'; ctx.lineWidth = 3; ctx.stroke();
  rr(96, 216, 888, 798, 28); ctx.fillStyle = '#f7f9fd'; ctx.fill(); ctx.save(); rr(96, 216, 888, 798, 28); ctx.clip();
  const item = asset(elapsed * 1000); if (item && (item.complete || item.readyState >= 2)) { ctx.globalAlpha = productMotion; if (mode === 'video') { contain(item, 118, 238, 844, 754); } else { const enter = ease(elapsed / .90), exiting = ease((p - .97) / .03), zoom = 1.16 - (.16 * enter) + (.07 * exiting), shift = ((1 - enter) * 50) - (exiting * 24); ctx.translate(540, 615 + shift); ctx.scale(zoom, zoom); ctx.translate(-540, -615); contain(item, 118, 238, 844, 754); } } else { ctx.fillStyle = '#e8edf6'; ctx.fillRect(96, 216, 888, 798); ctx.fillStyle = '#627291'; ctx.font = '700 34px Arial'; ctx.textAlign = 'center'; ctx.fillText('Add your product image or video', 540, 620); ctx.textAlign = 'left'; } ctx.restore();
  if (watermarkEnabled.checked) { ctx.globalAlpha = productMotion; rr(122, 950, 286, 48, 16); ctx.fillStyle = 'rgba(4,24,66,.76)'; ctx.fill(); ctx.fillStyle = 'rgba(255,255,255,.92)'; ctx.font = '700 20px Arial'; ctx.textAlign = 'center'; ctx.fillText(handleInput.value || '@Marketplace.Finds', 265, 981); ctx.textAlign = 'left'; ctx.globalAlpha = 1; }
  ctx.save(); ctx.globalAlpha = cardMotion; ctx.translate(0, (1 - cardMotion) * 38); ctx.shadowColor = 'rgba(0,7,25,.45)'; ctx.shadowBlur = 26; rr(70, 1060, 940, 460, 42); ctx.fillStyle = 'rgba(4,28,76,.96)'; ctx.fill(); ctx.restore(); rr(70, 1060, 940, 460, 42); ctx.strokeStyle = 'rgba(83,145,255,.82)'; ctx.lineWidth = 3; ctx.stroke(); rr(112, 1114, 144, 12, 6); ctx.fillStyle = '#ff9d00'; ctx.fill();
  ctx.save(); ctx.globalAlpha = hookMotion; ctx.translate((1 - hookMotion) * -26, 0); ctx.fillStyle = '#ffad18'; ctx.font = '800 29px Arial'; ctx.fillText(value('studio-hook', 'A smart find for everyday life').toUpperCase(), 112, 1172); ctx.restore();
  const titleLines = lines(value('studio-title', 'Your Product'), 820, '800 56px Arial'); ctx.save(); ctx.globalAlpha = titleMotion; ctx.translate(0, (1 - titleMotion) * 26); ctx.fillStyle = '#fff'; ctx.font = '800 56px Arial'; let y = 1244; titleLines.forEach((line) => { ctx.fillText(line, 112, y); y += 62; }); ctx.restore();
  ctx.save(); ctx.globalAlpha = benefitMotion; ctx.translate(0, (1 - benefitMotion) * 18); ctx.fillStyle = '#c7d6f2'; ctx.font = '600 24px Arial'; let benefitY = 1262 + (titleLines.length * 62); lines(value('studio-benefit', 'Add one useful benefit here'), 800, ctx.font).forEach((line) => { ctx.fillText(line, 112, benefitY); benefitY += 35; }); ctx.restore();
  ctx.save(); ctx.globalAlpha = priceMotion; ctx.translate((1 - priceMotion) * -38, 0); rr(112, 1442, 312, 58, 20); ctx.fillStyle = '#163b87'; ctx.fill(); ctx.strokeStyle = 'rgba(120,169,255,.65)'; ctx.lineWidth = 2; ctx.stroke(); ctx.fillStyle = '#fff'; ctx.font = '800 28px Arial'; ctx.fillText(value('studio-price', 'AED -'), 140, 1481); ctx.restore();
  ctx.save(); ctx.globalAlpha = ctaMotion; ctx.translate((1 - ctaMotion) * 38, 0); rr(600, 1442, 360, 58, 20); ctx.fillStyle = '#ff9d00'; ctx.fill(); ctx.fillStyle = '#071b43'; ctx.font = '800 21px Arial'; ctx.textAlign = 'center'; ctx.fillText(value('studio-cta', 'Find it on Amazon UAE'), 780, 1481); ctx.restore();
  ctx.globalAlpha = 1; ctx.textAlign = 'left'; requestAnimationFrame(render);
}
function clearMedia() { images.forEach((x) => URL.revokeObjectURL(x.src)); images = []; if (video) URL.revokeObjectURL(video.src); video = null; imageOrderList.innerHTML = ''; imageOrderControl.hidden = true; }
function renderImageOrder() { imageOrderList.innerHTML = ''; images.forEach((image, index) => { const row = document.createElement('div'); row.className = 'image-order-row'; const name = document.createElement('span'); name.textContent = image.dataset.fileName || `Image ${index + 1}`; const label = document.createElement('label'); label.textContent = 'Show as '; const select = document.createElement('select'); for (let position = 1; position <= images.length; position += 1) { const option = document.createElement('option'); option.value = position; option.textContent = position; option.selected = position === index + 1; select.append(option); } select.addEventListener('change', () => { const nextIndex = Number(select.value) - 1; const [moved] = images.splice(index, 1); images.splice(nextIndex, 0, moved); clipStart = performance.now(); renderImageOrder(); }); label.append(select); row.append(name, label); imageOrderList.append(row); }); imageOrderControl.hidden = images.length < 2; }
function setMode(next) { mode = next; clearMedia(); mediaInput.value = ''; const isVideo = mode === 'video'; mediaInput.accept = isVideo ? 'video/mp4,video/webm,video/quicktime' : 'image/png,image/jpeg,image/webp'; mediaInput.multiple = !isVideo; mediaHint.textContent = isVideo ? 'Choose one product video' : 'Add up to 10 images. You can add more later.'; }
mediaInput.addEventListener('change', async () => { studioMessage.textContent = ''; const files = [...mediaInput.files]; if (!files.length) return; if (mode === 'video') { clearMedia(); video = document.createElement('video'); video.src = URL.createObjectURL(files[0]); video.muted = true; video.loop = true; video.playsInline = true; const loaded = await new Promise((done) => { video.onloadeddata = () => done(true); video.onerror = () => done(false); }); if (!loaded) { studioMessage.textContent = 'This video could not be previewed. Please use an H.264 MP4, WebM, or MOV file.'; video = null; return; } await video.play().catch(() => {}); studioMessage.style.color = '#257449'; studioMessage.textContent = `Video ready. The export will use the first ${videoLength()} seconds.`; } else { const room = Math.max(0, 10 - images.length); const selected = files.slice(0, room); const added = (await Promise.all(selected.map((file) => new Promise((done) => { const image = new Image(); image.src = URL.createObjectURL(file); image.dataset.fileName = file.name; image.onload = () => done(image); image.onerror = () => done(null); })))).filter(Boolean); images.push(...added); renderImageOrder(); studioMessage.style.color = '#257449'; studioMessage.textContent = files.length > room ? `Added ${added.length} image(s). The limit is 10 images.` : `${images.length} images ready. Each image stays on screen for 4 seconds.`; } mediaInput.value = ''; clipStart = performance.now(); });
document.querySelectorAll('input[name="media-mode"]').forEach((el) => el.addEventListener('change', () => setMode(el.value)));
function download(blob, name) { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
document.getElementById('download-image').addEventListener('click', () => { clipStart = performance.now() - 2000; requestAnimationFrame(() => canvas.toBlob((blob) => download(blob, 'marketplace-finds-cover.png'), 'image/png')); });
document.getElementById('download-video').addEventListener('click', async () => { if (exporting) return; exporting = true; const button = document.getElementById('download-video'), choice = document.getElementById('video-format').value, duration = videoLength(); const mp4Type = MediaRecorder.isTypeSupported('video/mp4;codecs=avc1') ? 'video/mp4;codecs=avc1' : MediaRecorder.isTypeSupported('video/mp4') ? 'video/mp4' : ''; const type = choice === 'webm' ? 'video/webm;codecs=vp9' : choice === 'mp4' ? (mp4Type || 'video/webm;codecs=vp9') : (mp4Type || 'video/webm;codecs=vp9'); const extension = type.startsWith('video/mp4') ? 'mp4' : 'webm'; button.disabled = true; button.textContent = 'Creating video...'; const recorder = new MediaRecorder(canvas.captureStream(30), { mimeType: MediaRecorder.isTypeSupported(type) ? type : 'video/webm', videoBitsPerSecond: 6000000 }); const chunks = []; recorder.ondataavailable = (e) => e.data.size && chunks.push(e.data); recorder.onstop = () => { download(new Blob(chunks, { type: recorder.mimeType }), `marketplace-finds-tiktok-video.${extension}`); button.disabled = false; button.textContent = 'Download video'; exporting = false; studioMessage.style.color = '#257449'; studioMessage.textContent = extension === 'mp4' ? 'MP4 video downloaded.' : 'WebM video downloaded. TikTok accepts WebM uploads.'; }; if (video) { video.currentTime = 0; await video.play().catch(() => {}); } clipStart = performance.now(); recorder.start(); setTimeout(() => { recorder.stop(); if (video) video.pause(); }, duration * 1000); });
document.getElementById('studio-sign-out').addEventListener('click', async () => { await studioDb.auth.signOut(); window.location.href = 'admin.html'; });
studioDb.auth.getSession().then(({ data: { session } }) => { if (!session) { window.location.href = 'admin.html'; return; } document.getElementById('studio-loading').hidden = true; document.getElementById('studio-shell').hidden = false; render(); });
